"""Metric definition seed rows for the MVP reference dataset."""

from __future__ import annotations


def _metric(
    *,
    metric_key: str,
    module_key: str,
    name: str,
    description: str,
    frequency: str,
    unit: str,
    lag_category: str,
    weight: float,
    expected_direction_citadel: str,
    expected_direction_citrini: str,
    primary_feature_key: str,
    signal_transform: str,
    min_history_points: int,
    is_leading: bool,
    config: dict,
) -> dict:
    return {
        "metric_key": metric_key,
        "module_key": module_key,
        "name": name,
        "description": description,
        "frequency": frequency,
        "unit": unit,
        "lag_category": lag_category,
        "weight": weight,
        "expected_direction_citadel": expected_direction_citadel,
        "expected_direction_citrini": expected_direction_citrini,
        "primary_feature_key": primary_feature_key,
        "signal_transform": signal_transform,
        "min_history_points": min_history_points,
        "is_leading": is_leading,
        "config": config,
        "is_active": True,
    }


METRIC_DEFINITION_SEED_ROWS: list[dict] = [
    _metric(
        metric_key="ai_adoption_work_total",
        module_key="diffusion",
        name="AI adoption at work",
        description="Share of workers reporting AI use at work",
        frequency="monthly",
        unit="share",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="ai_adoption_work_daily",
        module_key="diffusion",
        name="Daily AI use",
        description="Share of workers using AI daily",
        frequency="monthly",
        unit="share",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="hours_saved_per_week_ai_users",
        module_key="diffusion",
        name="Hours saved by AI users",
        description="Weekly hours saved reported by AI users",
        frequency="monthly",
        unit="hours",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="labor_productivity_yoy",
        module_key="productivity",
        name="Labor productivity YoY",
        description="US labor productivity annual growth",
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=4,
        is_leading=False,
        config={"source_key": "fred", "series_id": "OPHNFB"},
    ),
    _metric(
        metric_key="revenue_per_employee_large_tech",
        module_key="productivity",
        name="Revenue per employee",
        description="Large tech revenue per employee",
        frequency="quarterly",
        unit="usd",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=4,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="software_postings_yoy",
        module_key="labor",
        name="Software postings YoY",
        description="Software job postings year-over-year",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.30,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="pm_postings_yoy",
        module_key="labor",
        name="PM postings YoY",
        description="Product management job postings year-over-year",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="finance_ops_postings_yoy",
        module_key="labor",
        name="Finance and ops postings YoY",
        description="Finance and ops job postings year-over-year",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="layoffs_white_collar_count",
        module_key="labor",
        name="White-collar layoff count",
        description="Count of public white-collar layoff events",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=1.25,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"source_key": "rss_corporate_ir"},
    ),
    _metric(
        metric_key="unemployment_rate_professional_services",
        module_key="labor",
        name="Unemployment professional services",
        description="Unemployment rate in professional services",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"source_key": "fred", "series_id": "UNRATE"},
    ),
    _metric(
        metric_key="discretionary_spending_high_income",
        module_key="demand",
        name="Discretionary spending high income",
        description="High-income discretionary spending proxy",
        frequency="monthly",
        unit="index",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="restaurant_spending_high_income",
        module_key="demand",
        name="Restaurant spending high income",
        description="High-income restaurant spending proxy",
        frequency="weekly",
        unit="index",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="trend_4w",
        signal_transform="lower_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="travel_spending_high_income",
        module_key="demand",
        name="Travel spending high income",
        description="High-income travel spending proxy",
        frequency="weekly",
        unit="index",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="trend_4w",
        signal_transform="lower_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="savings_rate_high_income",
        module_key="demand",
        name="Savings rate high income",
        description="High-income savings rate proxy",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="neutral",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="saas_renewal_discount_mentions",
        module_key="intermediation",
        name="SaaS renewal discount mentions",
        description="Textual mentions of renewal pressure",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_corporate_ir"},
    ),
    _metric(
        metric_key="ai_build_vs_buy_mentions",
        module_key="intermediation",
        name="Build vs buy mentions",
        description="Textual mentions of AI build-vs-buy substitution",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_corporate_ir"},
    ),
    _metric(
        metric_key="card_interchange_pressure_mentions",
        module_key="intermediation",
        name="Interchange pressure mentions",
        description="Textual mentions of interchange or pricing pressure",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_macro"},
    ),
    _metric(
        metric_key="marketplace_take_rate_pressure_mentions",
        module_key="intermediation",
        name="Marketplace take-rate pressure mentions",
        description="Textual mentions of marketplace take-rate pressure",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_macro"},
    ),
    _metric(
        metric_key="prime_mortgage_delinquency_tech_metros",
        module_key="credit_housing",
        name="Prime mortgage delinquency tech metros",
        description="Prime delinquency rate in tech-heavy metros",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="heloc_draws_tech_metros",
        module_key="credit_housing",
        name="HELOC draws tech metros",
        description="HELOC draws in tech-heavy metros",
        frequency="monthly",
        unit="usd",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="home_price_yoy_sf",
        module_key="credit_housing",
        name="SF home prices YoY",
        description="San Francisco home price growth",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="home_price_yoy_seattle",
        module_key="credit_housing",
        name="Seattle home prices YoY",
        description="Seattle home price growth",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="revolving_balance_high_income",
        module_key="credit_housing",
        name="Revolving balance high income",
        description="High-income revolving credit proxy",
        frequency="monthly",
        unit="usd",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    # --- India IT proxy metrics ---
    # TCS+Big4 headcount (thousands). YoY decline = citrini (white-collar substitution).
    _metric(
        metric_key="india_it_headcount_total",
        module_key="labor",
        name="India IT Big-4 headcount",
        description="Combined headcount of TCS, Infosys, Wipro, HCL (thousands). Proxy for global white-collar IT labor demand.",
        frequency="quarterly",
        unit="thousands",
        lag_category="confirmatory",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "india_it_earnings", "manual": True},
    ),
    # Revenue per employee (USD thousands). Rising = productivity proxy = citadel.
    _metric(
        metric_key="india_it_revenue_per_employee",
        module_key="productivity",
        name="India IT revenue per employee",
        description="TCS annualized revenue divided by headcount (USD thousands). Rising with flat/falling headcount = AI productivity gains.",
        frequency="quarterly",
        unit="usd_thousands",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "india_it_earnings", "manual": True},
    ),
    # AI revenue as % of total TCS revenue. Growing share = diffusion signal.
    _metric(
        metric_key="india_it_ai_revenue_pct",
        module_key="diffusion",
        name="India IT AI revenue share",
        description="TCS annualized AI revenue as fraction of total revenue. Measures enterprise AI adoption speed at scale.",
        frequency="quarterly",
        unit="share",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "india_it_earnings", "manual": True},
    ),
    # Wipro utilization rate. High utilization + flat headcount = productivity leverage.
    _metric(
        metric_key="india_it_utilization_rate",
        module_key="productivity",
        name="India IT utilization rate",
        description="Wipro billable utilization rate. Higher utilization with same headcount signals AI-driven output efficiency.",
        frequency="quarterly",
        unit="share",
        lag_category="leading",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="neutral",
        primary_feature_key="level",
        signal_transform="higher_is_citadel",
        min_history_points=3,
        is_leading=True,
        config={"source_key": "india_it_earnings", "manual": True},
    ),
    # --- Expanded proxy metrics (data pending fetch — see NEXT-ACTIONS.md) ---
    # Per-company India Big-4 breakouts (currently aggregate only)
    _metric(
        metric_key="infosys_headcount",
        module_key="labor",
        name="Infosys headcount",
        description="Infosys employee count. Per-company breakout from Big-4 aggregate to detect divergence within India IT.",
        frequency="quarterly",
        unit="thousands",
        lag_category="confirmatory",
        weight=0.50,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "india_it_earnings", "manual": True, "active": False},
    ),
    _metric(
        metric_key="hcl_headcount",
        module_key="labor",
        name="HCL Tech headcount",
        description="HCL Technologies employee count. Per-company breakout from Big-4 aggregate.",
        frequency="quarterly",
        unit="thousands",
        lag_category="confirmatory",
        weight=0.50,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "india_it_earnings", "manual": True, "active": False},
    ),
    # Cognizant: US-listed, India-heavy delivery. Cross-checks India IT pattern outside Big-4.
    _metric(
        metric_key="cognizant_headcount",
        module_key="labor",
        name="Cognizant headcount",
        description="Cognizant employee count. Cross-checks whether India IT compression generalizes to US-listed peers.",
        frequency="quarterly",
        unit="thousands",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "cognizant_earnings", "manual": True, "active": False},
    ),
    _metric(
        metric_key="cognizant_ai_revenue_pct",
        module_key="diffusion",
        name="Cognizant AI revenue share",
        description="Cognizant AI revenue as fraction of total. Independent confirmation of TCS AI revenue trajectory.",
        frequency="quarterly",
        unit="share",
        lag_category="leading",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "cognizant_earnings", "manual": True, "active": False},
    ),
    # Capgemini: European IT services. Geographic regression test.
    _metric(
        metric_key="capgemini_headcount",
        module_key="labor",
        name="Capgemini headcount",
        description="Capgemini employee count. Tests if India IT pattern replicates in European IT services.",
        frequency="quarterly",
        unit="thousands",
        lag_category="confirmatory",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "capgemini_earnings", "manual": True, "active": False},
    ),
    # Accenture: most-recent disclosure (different fiscal year, ends Aug-Feb-May-Aug).
    _metric(
        metric_key="accenture_headcount",
        module_key="labor",
        name="Accenture headcount",
        description="Accenture employee count. Forward signal vs India IT (different fiscal year).",
        frequency="quarterly",
        unit="thousands",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=5,
        is_leading=False,
        config={"source_key": "accenture_earnings", "manual": True, "active": False},
    ),
    _metric(
        metric_key="accenture_genai_bookings_pct",
        module_key="diffusion",
        name="Accenture GenAI bookings share",
        description="Accenture GenAI bookings as fraction of total bookings. Demand-side AI penetration signal.",
        frequency="quarterly",
        unit="share",
        lag_category="leading",
        weight=0.85,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "accenture_earnings", "manual": True, "active": False},
    ),
    # Microsoft: demand-side counterpart. Copilot enterprise seat count.
    _metric(
        metric_key="microsoft_copilot_seats",
        module_key="diffusion",
        name="Microsoft Copilot enterprise seats",
        description="Disclosed enterprise Copilot seat count. Direct AI demand signal at the customer side.",
        frequency="quarterly",
        unit="seats_millions",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "microsoft_earnings", "manual": True, "active": False},
    ),
    _metric(
        metric_key="microsoft_azure_ai_revenue_yoy",
        module_key="diffusion",
        name="Azure AI revenue YoY",
        description="Azure AI services revenue growth. Compute-side demand signal.",
        frequency="quarterly",
        unit="percent",
        lag_category="leading",
        weight=0.95,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="adoption_only",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "microsoft_earnings", "manual": True, "active": False},
    ),
    # BLS Employment Cost Index — white-collar wage growth.
    # Citrini: wage growth stagnates while productivity rises = employer captures gains.
    # Citadel: wage growth tracks productivity = workers share gains.
    _metric(
        metric_key="eci_white_collar_yoy",
        module_key="labor",
        name="ECI white-collar YoY",
        description="BLS Employment Cost Index, professional/management occupations. Stagnation while productivity rises = citrini margin capture.",
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=4,
        is_leading=False,
        config={
            "source_key": "bls_eci",
            "series_id": "CIU2020000000000A",
            "active": False,
        },
    ),
    # Indeed AI-exposed postings — leading indicator vs Harvard's lagging hiring study.
    _metric(
        metric_key="indeed_ai_exposed_yoy",
        module_key="labor",
        name="Indeed AI-exposed postings YoY",
        description="Indeed Hiring Lab index of AI-exposed occupation postings. Leading indicator of white-collar labor compression.",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"source_key": "indeed_hiring_lab", "active": False},
    ),
    # Earnings call transcript text mining.
    _metric(
        metric_key="earnings_call_ai_mentions_yoy",
        module_key="diffusion",
        name="S&P 500 'AI' transcript mention YoY",
        description="Frequency of 'AI', 'agent', 'automate' in S&P 500 earnings call transcripts. Adoption rhetoric vs reality.",
        frequency="quarterly",
        unit="percent",
        lag_category="leading",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="adoption_only",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "transcript_mentions", "manual": True, "active": False},
    ),
    _metric(
        metric_key="earnings_call_headcount_reduction_mentions",
        module_key="labor",
        name="'Headcount reduction' transcript mentions",
        description="Frequency of 'headcount reduction', 'workforce optimization' in S&P 500 calls. Citrini-direct rhetoric signal.",
        frequency="quarterly",
        unit="count",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "transcript_mentions", "manual": True, "active": False},
    ),
    # Big Law associate hiring — premium white-collar canary.
    _metric(
        metric_key="biglaw_associate_offers_yoy",
        module_key="labor",
        name="Big Law associate offers YoY",
        description="Top-100 NY law firm summer associate offer count. Premium white-collar canary; high pay = high AI substitution incentive.",
        frequency="annual",
        unit="percent",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=3,
        is_leading=False,
        config={"source_key": "nalp_law_hiring", "manual": True, "active": False},
    ),
    # =========================================================================
    # FALSIFIER METRICS (added 2026-05-10) — instrument the 4 citrini-falsifiers
    # surfaced via web-search synthesis. Sources: FRED-public + manual quarterly
    # for PE-SaaS watchlist (private credit data not free).
    # =========================================================================
    # --- F1: PE-backed SaaS distress (module: intermediation) ---
    _metric(
        metric_key="hy_oas_software_proxy",
        module_key="intermediation",
        name="High-yield OAS — proxy for SaaS-loaded HY tranche",
        description=(
            "ICE BofA US HY OAS (BAMLH0A0HYM2). Proxy — wide market. Citrini-confirming "
            "if widens >150bps over 4 weeks coinciding with iShares Expanded Tech-Software ETF (IGV) underperformance. PE-backed SaaS distress hits HY tranche first."
        ),
        frequency="daily",
        unit="basis_points",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=20,
        is_leading=True,
        config={"source_key": "fred", "series_id": "BAMLH0A0HYM2"},
    ),
    _metric(
        metric_key="commercial_industrial_loans_4w",
        module_key="intermediation",
        name="Commercial & industrial loans — 4-week change",
        description=(
            "BUSLOANS (commercial & industrial loans, all commercial banks). "
            "PE-backed SaaS refinancings show up here. Sharp 4-week deceleration "
            "is citrini-confirming (credit channel tightening)."
        ),
        frequency="weekly",
        unit="percent_change",
        lag_category="confirmatory",
        weight=0.85,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="pct_change_4w",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=False,
        config={"source_key": "fred", "series_id": "BUSLOANS"},
    ),
    _metric(
        metric_key="pe_saas_watchlist_distressed_pct",
        module_key="intermediation",
        name="PE-backed SaaS watchlist — distressed share",
        description=(
            "Manual quarterly: % of tracked PE-backed software loans trading <80¢. "
            "Watchlist: New Relic, Zendesk, Smartsheet, Hyland, Calabrio, Qlik DI. "
            "Anchors: Medallia (Thoma Bravo $5.1B equity wiped Feb 2026), Pluralsight "
            "(Vista $4B wiped 2024). Citrini-confirming if pct >= 30%."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.30,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=False,
        config={
            "source_key": "pe_saas_watchlist_manual",
            "manual": True,
            "watchlist": [
                "new_relic",
                "zendesk",
                "smartsheet",
                "hyland",
                "calabrio",
                "qlik_data_integration",
            ],
            "active": True,
        },
    ),
    # --- F2: Velocity of money (module: demand) ---
    _metric(
        metric_key="m2_velocity",
        module_key="demand",
        name="M2 velocity of money",
        description=(
            "FRED M2V. Citrini predicts velocity stabilizing/declining as machines hold "
            "income but don't spend (ghost GDP mechanism). >=2 consecutive quarters "
            "decline is citrini-confirming. Citadel predicts velocity recovers with productivity."
        ),
        frequency="quarterly",
        unit="ratio",
        lag_category="confirmatory",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="level",
        signal_transform="lower_is_citrini",
        min_history_points=4,
        is_leading=False,
        config={"source_key": "fred", "series_id": "M2V"},
    ),
    # --- F3: Mortgage market pressure (module: credit_housing) ---
    _metric(
        metric_key="mortgage_30y_rate",
        module_key="credit_housing",
        name="30-Year fixed mortgage rate",
        description="FRED MORTGAGE30US. Composite signal with delinquency + price decline.",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=0.80,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"source_key": "fred", "series_id": "MORTGAGE30US"},
    ),
    _metric(
        metric_key="commercial_re_delinquency",
        module_key="credit_housing",
        name="Commercial real estate delinquency rate",
        description=(
            "FRED DRCRELACBS. Lagging but high-confidence. Citrini predicts mortgage "
            "cascade; CRE typically rises first. Citrini-confirming if >=1.5% sustained 2Q."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=False,
        config={"source_key": "fred", "series_id": "DRCRELACBS"},
    ),
    _metric(
        metric_key="case_shiller_national_yoy",
        module_key="credit_housing",
        name="S&P/Case-Shiller national home price YoY",
        description=(
            "FRED CSUSHPISA. Citrini predicts price decline from white-collar income "
            "compression. Sustained YoY <0 is citrini-confirming."
        ),
        frequency="monthly",
        unit="index",
        lag_category="confirmatory",
        weight=0.95,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=12,
        is_leading=False,
        config={"source_key": "fred", "series_id": "CSUSHPISA"},
    ),
    # --- F4: White-collar unemployment 25+ (module: labor) ---
    _metric(
        metric_key="unemployment_25plus_management_professional",
        module_key="labor",
        name="Unemployment 25+ — management/professional",
        description=(
            "BLS LNS14000048 (unemployment, 25+, management/professional/related). "
            "Extends Brynjolfsson finding from <25 to 25+ pop. Citrini-confirming if "
            "YoY change >=0.5pp sustained 3 months."
        ),
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.40,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={
            "source_key": "bls_extended",
            "series_id": "LNS14000048",
            "active": True,
        },
    ),
    _metric(
        metric_key="eci_professional_management_yoy",
        module_key="labor",
        name="ECI professional/management compensation YoY",
        description=(
            "FRED CIU2020000000000A. Wage growth in white-collar premium. "
            "Deceleration is citrini-confirming (income compression channel)."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.85,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=4,
        is_leading=False,
        config={"source_key": "fred", "series_id": "CIU2020000000000A"},
    ),
    # =========================================================================
    # THIRD-THESIS METRICS (module: infrastructure) — 2026-05-10
    # Emerged from adjacent-possible web search. Neither citrini nor citadel
    # modeled power/compute as deployment rate-limiter. Captures throttle on
    # agentic AI scaling (Reynolds coefficient of citrini's reflexivity model).
    # =========================================================================
    _metric(
        metric_key="datacenter_capacity_delay_pct",
        module_key="infrastructure",
        name="Data center capacity — % of planned GW delayed",
        description=(
            "Manual quarterly: % of announced 2026 capacity cancelled/slipped to 2028+. "
            "Source: Sightline Climate + Bloomberg. Baseline 2026 Q2: 7 of 12 GW = 58%. "
            "Higher = more throttle on citrini timeline. Third-thesis: not "
            "citrini/citadel-axis-aligned, but reshapes both."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="leading",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={
            "source_key": "infrastructure_manual",
            "manual": True,
            "baseline_2026_q2": 0.58,
            "note": "Higher = slower citrini timeline, citadel buys time.",
            "active": True,
        },
    ),
    _metric(
        metric_key="transformer_lead_time_months",
        module_key="infrastructure",
        name="High-voltage transformer lead time (months)",
        description=(
            "Manual quarterly. Baseline 2026 Q2: 36-48 months (vs 12-18 pre-2024). "
            "Source: industry reports + Bernstein research. Physical rate-limiter "
            "on agentic AI deployment."
        ),
        frequency="quarterly",
        unit="months",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="down",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={
            "source_key": "infrastructure_manual",
            "manual": True,
            "baseline_2026_q2": 42,
            "active": True,
        },
    ),
    _metric(
        metric_key="us_datacenter_electricity_share",
        module_key="infrastructure",
        name="US data center electricity consumption share",
        description=(
            "EIA + DOE/LBNL projections. Baseline 2026 Q2: ~4.4% (176 TWh annual). "
            "DOE projects up to 12% by 2030. Hard ceiling on agentic deployment."
        ),
        frequency="annual",
        unit="share",
        lag_category="confirmatory",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=False,
        config={
            "source_key": "infrastructure_manual",
            "manual": True,
            "baseline_2026_q2": 0.044,
            "active": True,
        },
    ),
    _metric(
        metric_key="hbm_cowos_capacity_booked_pct",
        module_key="infrastructure",
        name="CoWoS/HBM advanced packaging capacity booked",
        description=(
            "Manual quarterly: % of TSMC CoWoS capacity pre-booked through next 12mo. "
            "Baseline 2026 Q2: Nvidia ~50% alone. Tight binding constraint upstream of "
            "data center deployment. Caps agentic scaling rate."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="leading",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={
            "source_key": "infrastructure_manual",
            "manual": True,
            "baseline_2026_q2": 0.55,
            "active": True,
        },
    ),
    # ═══════════════════════════════════════════════════════════════════════════════
    # EMERGENT THESIS MODULES — surfaced by /thesis-update 2026-07-07 (Bradford-respected,
    # 18 WebSearches, every value URL-cited in outputs/thesis-update-2026-07-07.md).
    # These score on their OWN module rows — NOT folded into citadel/citrini (per the skill).
    # ═══════════════════════════════════════════════════════════════════════════════
    #
    # ── open_source_deflation: Chinese open-weight models commoditize frontier value
    #    faster than capex is recouped. Graduated from May-2026 candidate → primary force.
    _metric(
        metric_key="chinese_model_token_share_openrouter",
        module_key="deflation",
        name="Chinese-model token share (OpenRouter, US companies)",
        description=(
            "Share of tokens from US companies routed to Chinese open-weight models on OpenRouter. "
            "2026-07: >30% every week since Feb 8 (peaked 46%) vs 11% trailing-12mo and 4.5% H1'25. "
            "Platform-wide Chinese share ~51% (Apr); US-model share collapsed 70%->30% Jun'25->Jun'26. "
            "Rising = open-source-deflation thesis stronger."
        ),
        frequency="weekly",
        unit="share",
        lag_category="leading",
        weight=1.30,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "deflation_manual", "manual": True, "emergent_thesis": "open_source_deflation", "baseline_2026_07": 0.30, "peak": 0.46},
    ),
    _metric(
        metric_key="frontier_token_price_usd_per_m",
        module_key="deflation",
        name="Blended paid token price (USD/M)",
        description=(
            "Blended price per million tokens paid by users: ~$1.90 (late 2024) -> ~$0.65 (May 2026). "
            "GPT-4-class $20/M (2022) -> ~$0.40/M (2026) ~= 1000x. Falling = deflation. "
            "Counter (Jevons): see token_consumption_volume — volume 19x offsets the price drop."
        ),
        frequency="monthly",
        unit="usd",
        lag_category="leading",
        weight=1.20,
        expected_direction_citadel="down",
        expected_direction_citrini="down",
        primary_feature_key="level",
        signal_transform="lower_is_citrini",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "deflation_manual", "manual": True, "emergent_thesis": "open_source_deflation", "baseline_2026_05": 0.65},
    ),
    _metric(
        metric_key="us_frontier_lab_price_cut_events",
        module_key="deflation",
        name="US frontier lab price-cut events",
        description=(
            "Count of US frontier labs cutting API prices under Chinese-open pressure. 2026-06-30: "
            "Anthropic cut (Sonnet 5 $2/$10 vs Opus $5/$25). OpenAI weighing (Altman: 'costs a huge "
            "issue', unconfirmed as of Jul 2). Deflation reaching the PROVIDER layer = 'margin "
            "recovery is a math problem with no clean solution'."
        ),
        frequency="monthly",
        unit="count",
        lag_category="confirmatory",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "deflation_manual", "manual": True, "emergent_thesis": "open_source_deflation", "baseline_2026_07": 1},
    ),
    _metric(
        metric_key="intelligence_gap_us_china_open",
        module_key="deflation",
        name="Capability gap: best US vs best Chinese open model",
        description=(
            "Artificial Analysis Intelligence Index points between best US (Opus 4.8 ~55.7) and best "
            "Chinese open-weight (GLM-5.2 ~51) = ~4.7, shrinking. Stanford AI Index (Arena): US-China "
            "gap collapsed to 2.7%. Narrowing = deflation thesis stronger (cheap ~= good-enough)."
        ),
        frequency="quarterly",
        unit="index",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="level",
        signal_transform="lower_is_citrini",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "deflation_manual", "manual": True, "emergent_thesis": "open_source_deflation", "baseline_2026_q2": 4.7},
    ),
    _metric(
        metric_key="india_it_ai_deflation_guidance",
        module_key="deflation",
        name="India IT AI-deflation revenue guidance",
        description=(
            "AI deflation now in the India IT proxy the monitor already tracks: HCL CEO guides future "
            "revenue DIPS 3-5% from AI deflation; Infosys expects deflation to become a factor. Links "
            "the deflation thesis to the labor/diffusion proxy."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="level",
        signal_transform="lower_is_citrini",
        min_history_points=1,
        is_leading=False,
        config={"source_key": "india_it_manual", "manual": True, "emergent_thesis": "open_source_deflation", "baseline_2026": -4.0},
    ),
    _metric(
        metric_key="token_consumption_volume_monthly",
        module_key="deflation",
        name="Total paid token consumption (Jevons falsifier)",
        description=(
            "FALSIFIER of the deflation-bear read: monthly paid token volume ~24,000B by May 2026, "
            "~19x from late 2024, EVEN AS price/M fell $1.90->$0.65. Jevons — cheaper intelligence "
            "expands the market. Rising fast = deflation may GROW revenue, not kill it."
        ),
        frequency="monthly",
        unit="index",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citadel",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "deflation_manual", "manual": True, "emergent_thesis": "open_source_deflation", "role": "falsifier", "baseline_2026_05_billions": 24000},
    ),
    #
    # ── ai_financing_fragility: circular Nvidia<->neocloud<->hyperscaler funding + GPU-collateral
    #    debt. Neither citadel nor citrini models the FINANCING structure. New 2026-07-07.
    _metric(
        metric_key="openai_commitments_to_revenue_ratio",
        module_key="financing_fragility",
        name="OpenAI compute commitments / revenue",
        description=(
            "OpenAI ~$600B compute target by 2030 (reset from $1.4T thru 2033; $1.09T infra deals: "
            "Oracle $300B, AMD $90B, AWS $38B) vs ~$13.1B revenue (2025). Ratio ~46x. CFO fears $1.5T "
            "commitments 'can't be paid'; needs $280B revenue by 2030. Circular: Nvidia->OpenAI->Nvidia."
        ),
        frequency="quarterly",
        unit="ratio",
        lag_category="leading",
        weight=1.20,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "financing_manual", "manual": True, "emergent_thesis": "ai_financing_fragility", "baseline_2026": 46.0},
    ),
    _metric(
        metric_key="gpu_collateral_debt_issuance_usd_bn",
        module_key="financing_fragility",
        name="AI data-center / GPU-collateral debt issuance ($bn)",
        description=(
            "AI DC debt issuance >$200bn (2025); Morgan Stanley $250-300bn hyperscaler 2026; IG "
            "issuance could top $2T in 2026. CoreWeave alone 3 GPU-backed loans $12.4bn + $8.5bn IG. "
            "GPU 7yr lifecycle vs 20-30yr facility = mismatch; first maturities 2026-27. Fed/BIS/Treasury/4-senators warned."
        ),
        frequency="quarterly",
        unit="usd",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "financing_manual", "manual": True, "emergent_thesis": "ai_financing_fragility", "baseline_2025_billions": 200},
    ),
    #
    # ── power_bottleneck: electricity (not chips) is the binding constraint. Extends the
    #    existing `infrastructure` module (already home to the CoWoS throttle metric).
    _metric(
        metric_key="datacenter_capacity_delay_pct",
        module_key="infrastructure",
        name="Data center capacity delayed/cancelled",
        description=(
            "Share of planned data centers delayed/cancelled by grid. IEA: ~20% of planned projects at "
            "significant risk; Sightline: 30-50% of 2026 large DCs delayed/cancelled; 11 GW announced "
            "with no construction ('7 GW gap': 12-16 planned vs ~5 building). Utilities now question if "
            "the pipeline is real. Throttles agentic-deployment rate."
        ),
        frequency="quarterly",
        unit="percent",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "infrastructure_manual", "manual": True, "emergent_thesis": "power_bottleneck", "baseline_2026_q2": 0.20},
    ),
    _metric(
        metric_key="grid_interconnection_queue_months",
        module_key="infrastructure",
        name="Grid interconnection queue (months)",
        description=(
            "Wait for grid interconnection in key markets: 4-7yr (N.Virginia/Phoenix/Dallas), up to a "
            "decade in some regions. PJM queue 2,600 GW pending, avg >5yr. Transmission lines up to 8yr. "
            "Behind-the-meter gas (18-24mo) is the workaround. Binds the buildout more than GPU supply."
        ),
        frequency="quarterly",
        unit="months",
        lag_category="leading",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="third_thesis_throttle",
        min_history_points=1,
        is_leading=True,
        config={"source_key": "infrastructure_manual", "manual": True, "emergent_thesis": "power_bottleneck", "baseline_2026_q2_months": 60},
    ),
]
