"""Metric definition seed rows for the MVP reference dataset."""

from __future__ import annotations


def _metric(
    *,
    metric_key: str,
    module_key: str,
    name: str,
    description: str,
    frequency: str,
    unit: str,
    lag_category: str,
    weight: float,
    expected_direction_citadel: str,
    expected_direction_citrini: str,
    primary_feature_key: str,
    signal_transform: str,
    min_history_points: int,
    is_leading: bool,
    config: dict,
) -> dict:
    return {
        "metric_key": metric_key,
        "module_key": module_key,
        "name": name,
        "description": description,
        "frequency": frequency,
        "unit": unit,
        "lag_category": lag_category,
        "weight": weight,
        "expected_direction_citadel": expected_direction_citadel,
        "expected_direction_citrini": expected_direction_citrini,
        "primary_feature_key": primary_feature_key,
        "signal_transform": signal_transform,
        "min_history_points": min_history_points,
        "is_leading": is_leading,
        "config": config,
        "is_active": True,
    }


METRIC_DEFINITION_SEED_ROWS: list[dict] = [
    _metric(
        metric_key="ai_adoption_work_total",
        module_key="diffusion",
        name="AI adoption at work",
        description="Share of workers reporting AI use at work",
        frequency="monthly",
        unit="share",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="ai_adoption_work_daily",
        module_key="diffusion",
        name="Daily AI use",
        description="Share of workers using AI daily",
        frequency="monthly",
        unit="share",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="hours_saved_per_week_ai_users",
        module_key="diffusion",
        name="Hours saved by AI users",
        description="Weekly hours saved reported by AI users",
        frequency="monthly",
        unit="hours",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="adoption_only",
        min_history_points=1,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="labor_productivity_yoy",
        module_key="productivity",
        name="Labor productivity YoY",
        description="US labor productivity annual growth",
        frequency="quarterly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=4,
        is_leading=False,
        config={"source_key": "fred", "series_id": "OPHNFB"},
    ),
    _metric(
        metric_key="revenue_per_employee_large_tech",
        module_key="productivity",
        name="Revenue per employee",
        description="Large tech revenue per employee",
        frequency="quarterly",
        unit="usd",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citadel",
        min_history_points=4,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="software_postings_yoy",
        module_key="labor",
        name="Software postings YoY",
        description="Software job postings year-over-year",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.30,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="pm_postings_yoy",
        module_key="labor",
        name="PM postings YoY",
        description="Product management job postings year-over-year",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="finance_ops_postings_yoy",
        module_key="labor",
        name="Finance and ops postings YoY",
        description="Finance and ops job postings year-over-year",
        frequency="weekly",
        unit="percent",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="layoffs_white_collar_count",
        module_key="labor",
        name="White-collar layoff count",
        description="Count of public white-collar layoff events",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=1.25,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"source_key": "rss_corporate_ir"},
    ),
    _metric(
        metric_key="unemployment_rate_professional_services",
        module_key="labor",
        name="Unemployment professional services",
        description="Unemployment rate in professional services",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="level",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"source_key": "fred", "series_id": "UNRATE"},
    ),
    _metric(
        metric_key="discretionary_spending_high_income",
        module_key="demand",
        name="Discretionary spending high income",
        description="High-income discretionary spending proxy",
        frequency="monthly",
        unit="index",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="restaurant_spending_high_income",
        module_key="demand",
        name="Restaurant spending high income",
        description="High-income restaurant spending proxy",
        frequency="weekly",
        unit="index",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="trend_4w",
        signal_transform="lower_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="travel_spending_high_income",
        module_key="demand",
        name="Travel spending high income",
        description="High-income travel spending proxy",
        frequency="weekly",
        unit="index",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="trend_4w",
        signal_transform="lower_is_citrini",
        min_history_points=4,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="savings_rate_high_income",
        module_key="demand",
        name="Savings rate high income",
        description="High-income savings rate proxy",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="neutral",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="saas_renewal_discount_mentions",
        module_key="intermediation",
        name="SaaS renewal discount mentions",
        description="Textual mentions of renewal pressure",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=1.10,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_corporate_ir"},
    ),
    _metric(
        metric_key="ai_build_vs_buy_mentions",
        module_key="intermediation",
        name="Build vs buy mentions",
        description="Textual mentions of AI build-vs-buy substitution",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=1.00,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_corporate_ir"},
    ),
    _metric(
        metric_key="card_interchange_pressure_mentions",
        module_key="intermediation",
        name="Interchange pressure mentions",
        description="Textual mentions of interchange or pricing pressure",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_macro"},
    ),
    _metric(
        metric_key="marketplace_take_rate_pressure_mentions",
        module_key="intermediation",
        name="Marketplace take-rate pressure mentions",
        description="Textual mentions of marketplace take-rate pressure",
        frequency="weekly",
        unit="count",
        lag_category="leading",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="count_4w",
        signal_transform="higher_is_citrini",
        min_history_points=2,
        is_leading=True,
        config={"source_key": "rss_macro"},
    ),
    _metric(
        metric_key="prime_mortgage_delinquency_tech_metros",
        module_key="credit_housing",
        name="Prime mortgage delinquency tech metros",
        description="Prime delinquency rate in tech-heavy metros",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=1.20,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="heloc_draws_tech_metros",
        module_key="credit_housing",
        name="HELOC draws tech metros",
        description="HELOC draws in tech-heavy metros",
        frequency="monthly",
        unit="usd",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="home_price_yoy_sf",
        module_key="credit_housing",
        name="SF home prices YoY",
        description="San Francisco home price growth",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="home_price_yoy_seattle",
        module_key="credit_housing",
        name="Seattle home prices YoY",
        description="Seattle home price growth",
        frequency="monthly",
        unit="percent",
        lag_category="confirmatory",
        weight=0.80,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="yoy",
        signal_transform="lower_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
    _metric(
        metric_key="revolving_balance_high_income",
        module_key="credit_housing",
        name="Revolving balance high income",
        description="High-income revolving credit proxy",
        frequency="monthly",
        unit="usd",
        lag_category="confirmatory",
        weight=0.90,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="yoy",
        signal_transform="higher_is_citrini",
        min_history_points=6,
        is_leading=False,
        config={"manual": True},
    ),
]

