"""Metric definition seed rows for the MVP reference dataset."""

from __future__ import annotations


def _metric(
    *,
    metric_key: str,
    module_key: str,
    name: str,
    description: str,
    frequency: str,
    unit: str,
    lag_category: str,
    weight: float,
    expected_direction_citadel: str,
    expected_direction_citrini: str,
    primary_feature_key: str,
    signal_transform: str,
    min_history_points: int,
    config: dict,
    is_leading: bool = False,
) -> dict:
    return {
        "metric_key": metric_key,
        "module_key": module_key,
        "name": name,
        "description": description,
        "frequency": frequency,
        "unit": unit,
        "lag_category": lag_category,
        "weight": weight,
        "expected_direction_citadel": expected_direction_citadel,
        "expected_direction_citrini": expected_direction_citrini,
        "primary_feature_key": primary_feature_key,
        "signal_transform": signal_transform,
        "min_history_points": min_history_points,
        "is_leading": is_leading,
        "config": config,
        "is_active": True,
    }


METRIC_DEFINITION_SEED_ROWS: list[dict] = [
    _metric(
        metric_key="ai_adoption_work_total",
        module_key="diffusion",
        name="AI Adoption in Work (Total)",
        description="Share of workers reporting AI use at work.",
        frequency="monthly",
        unit="percent",
        lag_category="medium",
        weight=1.00,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="ai_adoption_work_total",
        signal_transform="level",
        min_history_points=6,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="ai_adoption_work_daily",
        module_key="diffusion",
        name="AI Adoption in Work (Daily Users)",
        description="Share of workers using AI daily for work tasks.",
        frequency="monthly",
        unit="percent",
        lag_category="medium",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="ai_adoption_work_daily",
        signal_transform="level",
        min_history_points=6,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="hours_saved_per_week_ai_users",
        module_key="diffusion",
        name="Hours Saved per Week by AI Users",
        description="Estimated weekly hours saved by AI users.",
        frequency="monthly",
        unit="hours",
        lag_category="medium",
        weight=0.85,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="hours_saved_per_week_ai_users",
        signal_transform="level",
        min_history_points=6,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="labor_productivity_yoy",
        module_key="productivity",
        name="Labor Productivity YoY",
        description="Year-over-year labor productivity growth.",
        frequency="quarterly",
        unit="percent",
        lag_category="high",
        weight=1.10,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="labor_productivity_yoy",
        signal_transform="yoy",
        min_history_points=12,
        config={"source_key": "fred", "series_id": "OPHNFB"},
    ),
    _metric(
        metric_key="revenue_per_employee_large_tech",
        module_key="productivity",
        name="Revenue per Employee (Large Tech)",
        description="Revenue per employee trend for large technology firms.",
        frequency="quarterly",
        unit="usd",
        lag_category="high",
        weight=0.95,
        expected_direction_citadel="up",
        expected_direction_citrini="up",
        primary_feature_key="revenue_per_employee_large_tech",
        signal_transform="yoy",
        min_history_points=8,
        config={"manual": True},
    ),
    _metric(
        metric_key="software_postings_yoy",
        module_key="labor",
        name="Software Postings YoY",
        description="Year-over-year trend in software job postings.",
        frequency="monthly",
        unit="percent",
        lag_category="low",
        weight=1.00,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="software_postings_yoy",
        signal_transform="yoy",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="pm_postings_yoy",
        module_key="labor",
        name="Product Manager Postings YoY",
        description="Year-over-year trend in product manager postings.",
        frequency="monthly",
        unit="percent",
        lag_category="low",
        weight=0.75,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="pm_postings_yoy",
        signal_transform="yoy",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="finance_ops_postings_yoy",
        module_key="labor",
        name="Finance/Ops Postings YoY",
        description="Year-over-year trend in finance and operations postings.",
        frequency="monthly",
        unit="percent",
        lag_category="low",
        weight=0.70,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="finance_ops_postings_yoy",
        signal_transform="yoy",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="layoffs_white_collar_count",
        module_key="labor",
        name="White Collar Layoff Count",
        description="Reported count of white-collar layoff events.",
        frequency="weekly",
        unit="count",
        lag_category="low",
        weight=0.85,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="layoffs_white_collar_count",
        signal_transform="level",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="unemployment_rate_professional_services",
        module_key="labor",
        name="Unemployment Rate (Professional Services)",
        description="Unemployment proxy from FRED for professional services exposure.",
        frequency="monthly",
        unit="percent",
        lag_category="medium",
        weight=0.90,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="unemployment_rate_professional_services",
        signal_transform="level",
        min_history_points=24,
        config={"source_key": "fred", "series_id": "UNRATE"},
    ),
    _metric(
        metric_key="discretionary_spending_high_income",
        module_key="demand",
        name="Discretionary Spending (High Income)",
        description="Discretionary spending trend for high-income cohorts.",
        frequency="monthly",
        unit="index",
        lag_category="low",
        weight=0.95,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="discretionary_spending_high_income",
        signal_transform="yoy",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="restaurant_spending_high_income",
        module_key="demand",
        name="Restaurant Spending (High Income)",
        description="Restaurant spending trend for high-income cohorts.",
        frequency="monthly",
        unit="index",
        lag_category="low",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="restaurant_spending_high_income",
        signal_transform="yoy",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="travel_spending_high_income",
        module_key="demand",
        name="Travel Spending (High Income)",
        description="Travel spending trend for high-income cohorts.",
        frequency="monthly",
        unit="index",
        lag_category="low",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="travel_spending_high_income",
        signal_transform="yoy",
        min_history_points=12,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="savings_rate_high_income",
        module_key="demand",
        name="Savings Rate (High Income)",
        description="Savings rate trend for high-income cohorts.",
        frequency="monthly",
        unit="percent",
        lag_category="medium",
        weight=0.60,
        expected_direction_citadel="down",
        expected_direction_citrini="up",
        primary_feature_key="savings_rate_high_income",
        signal_transform="level",
        min_history_points=12,
        config={"manual": True},
    ),
    _metric(
        metric_key="saas_renewal_discount_mentions",
        module_key="intermediation",
        name="SaaS Renewal Discount Mentions",
        description="Mentions of discounting pressure in SaaS renewals.",
        frequency="weekly",
        unit="count",
        lag_category="low",
        weight=0.85,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="saas_renewal_discount_mentions",
        signal_transform="level",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="ai_build_vs_buy_mentions",
        module_key="intermediation",
        name="AI Build vs Buy Mentions",
        description="Mentions of build-vs-buy decisions for AI tooling.",
        frequency="weekly",
        unit="count",
        lag_category="low",
        weight=0.75,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="ai_build_vs_buy_mentions",
        signal_transform="level",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="card_interchange_pressure_mentions",
        module_key="intermediation",
        name="Card Interchange Pressure Mentions",
        description="Mentions of interchange fee pressure in payments.",
        frequency="weekly",
        unit="count",
        lag_category="low",
        weight=0.65,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="card_interchange_pressure_mentions",
        signal_transform="level",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="marketplace_take_rate_pressure_mentions",
        module_key="intermediation",
        name="Marketplace Take Rate Pressure Mentions",
        description="Mentions of take-rate pressure in marketplace channels.",
        frequency="weekly",
        unit="count",
        lag_category="low",
        weight=0.65,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="marketplace_take_rate_pressure_mentions",
        signal_transform="level",
        min_history_points=8,
        is_leading=True,
        config={"manual": True},
    ),
    _metric(
        metric_key="prime_mortgage_delinquency_tech_metros",
        module_key="credit_housing",
        name="Prime Mortgage Delinquency (Tech Metros)",
        description="Prime mortgage delinquency trend in tech-focused metros.",
        frequency="quarterly",
        unit="percent",
        lag_category="high",
        weight=0.95,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="prime_mortgage_delinquency_tech_metros",
        signal_transform="yoy",
        min_history_points=8,
        config={"manual": True},
    ),
    _metric(
        metric_key="heloc_draws_tech_metros",
        module_key="credit_housing",
        name="HELOC Draws (Tech Metros)",
        description="HELOC draw trend in tech-focused metros.",
        frequency="quarterly",
        unit="index",
        lag_category="high",
        weight=0.70,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="heloc_draws_tech_metros",
        signal_transform="yoy",
        min_history_points=8,
        config={"manual": True},
    ),
    _metric(
        metric_key="home_price_yoy_sf",
        module_key="credit_housing",
        name="Home Price YoY (San Francisco)",
        description="Year-over-year home price change in San Francisco.",
        frequency="monthly",
        unit="percent",
        lag_category="medium",
        weight=0.60,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="home_price_yoy_sf",
        signal_transform="yoy",
        min_history_points=24,
        config={"manual": True},
    ),
    _metric(
        metric_key="home_price_yoy_seattle",
        module_key="credit_housing",
        name="Home Price YoY (Seattle)",
        description="Year-over-year home price change in Seattle.",
        frequency="monthly",
        unit="percent",
        lag_category="medium",
        weight=0.60,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="home_price_yoy_seattle",
        signal_transform="yoy",
        min_history_points=24,
        config={"manual": True},
    ),
    _metric(
        metric_key="revolving_balance_high_income",
        module_key="credit_housing",
        name="Revolving Balance (High Income)",
        description="Revolving balance trend for high-income cohorts.",
        frequency="monthly",
        unit="usd",
        lag_category="medium",
        weight=0.75,
        expected_direction_citadel="up",
        expected_direction_citrini="down",
        primary_feature_key="revolving_balance_high_income",
        signal_transform="yoy",
        min_history_points=12,
        config={"manual": True},
    ),
]

